import type { Metadata } from 'next';
import {Open_Sans} from 'next/font/google';
import './globals.css';
import {ReactNode} from 'react';

const inter = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};
 
export default function RootLayout({
	children
}: Readonly<{
  children: ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
